import type { Technology } from './model';
export const technologies: Technology[] = [
  { id: 'joblib', name: 'Joblib', category: 'Library', description: 'Persisting and loading Python model artifacts.' },
  { id: 'nextjs', name: 'Next.js', category: 'Framework', description: 'React application routing, rendering, and server composition.' },
  { id: 'react', name: 'React', category: 'Framework', description: 'Composable, state-driven web interfaces.' },
  { id: 'typescript', name: 'TypeScript', category: 'Language', description: 'Static types for application contracts and reusable modules.' },
  { id: 'tailwind', name: 'Tailwind CSS', category: 'Framework', description: 'Utility-based styling and responsive layout.' },
  { id: 'fastapi', name: 'FastAPI', category: 'Framework', description: 'Validated Python HTTP APIs.' },
  { id: 'python', name: 'Python', category: 'Language', description: 'Backend services, analytics, and machine learning workflows.' },
  { id: 'postgres', name: 'PostgreSQL', category: 'Database', description: 'Relational persistence with query and transaction support.' },
  { id: 'sqlalchemy', name: 'SQLAlchemy', category: 'Library', description: 'Python ORM and SQL database access.' },
  { id: 'langgraph', name: 'LangGraph', category: 'Framework', description: 'Stateful graph-based AI workflow orchestration.' },
  { id: 'openai', name: 'OpenAI SDK', category: 'Service', description: 'Client integration with model and embedding APIs.' },
  { id: 'reportlab', name: 'ReportLab', category: 'Library', description: 'Programmatic PDF document generation.' },
  { id: 'streamlit', name: 'Streamlit', category: 'Framework', description: 'Python interactive application widgets and session state.' },
  { id: 'pandas', name: 'Pandas', category: 'Library', description: 'Tabular preparation, validation, and aggregation.' },
  { id: 'numpy', name: 'NumPy', category: 'Library', description: 'Numerical arrays and calculations.' },
  { id: 'plotly', name: 'Plotly', category: 'Graphics', description: 'Interactive charts and analytical visualizations.' },
  { id: 'scikit-learn', name: 'Scikit-learn', category: 'Library', description: 'Machine learning estimators, preprocessing, and evaluation.' },
  { id: 'xgboost', name: 'XGBoost', category: 'Library', description: 'Gradient-boosted tree estimators.' },
  { id: 'shap', name: 'SHAP', category: 'Library', description: 'Model feature attribution and explanations.' },
  { id: 'flask', name: 'Flask', category: 'Framework', description: 'Python web routes and server-rendered applications.' },
  { id: 'javascript', name: 'JavaScript', category: 'Language', description: 'Browser interactions and application logic.' },
  { id: 'chartjs', name: 'Chart.js', category: 'Graphics', description: 'Browser-based analytical charts.' },
  { id: 'pgvector', name: 'pgvector', category: 'Database', description: 'PostgreSQL vector storage and similarity queries.' },
  { id: 'pymupdf', name: 'PyMuPDF', category: 'Library', description: 'PDF document inspection and text extraction.' },
  { id: 'transformers', name: 'Transformers', category: 'Library', description: 'Pretrained transformer model loading, training, and inference.' },
  { id: 'pytorch', name: 'PyTorch', category: 'Framework', description: 'Tensor computation and neural network execution.' },
  { id: 'torchvision', name: 'TorchVision', category: 'Library', description: 'Computer vision models and image transforms for PyTorch.' },
  { id: 'ultralytics', name: 'Ultralytics YOLO', category: 'Library', description: 'Pretrained object detection and vision model integration.' },
  { id: 'opencv', name: 'OpenCV', category: 'Library', description: 'Image processing and computer vision operations.' },
  { id: 'supabase', name: 'Supabase', category: 'Platform', description: 'Authentication, storage, and PostgreSQL services.' },
  { id: 'csv-parse', name: 'csv-parse', category: 'Library', description: 'Server-side CSV parsing for Node.js.' },
  { id: 'phaser', name: 'Phaser', category: 'Framework', description: 'Browser-based 2D game rendering and scenes.' },
  { id: 'express', name: 'Express', category: 'Framework', description: 'Node.js HTTP server and middleware.' },
  { id: 'nodejs', name: 'Node.js', category: 'Platform', description: 'JavaScript server execution.' },
  { id: 'socketio', name: 'Socket.IO', category: 'Library', description: 'Event-based realtime client/server communication.' },
  { id: 'redis', name: 'Redis', category: 'Database', description: 'In-memory shared state, caching, and queues.' },
  { id: 'prisma', name: 'Prisma', category: 'Library', description: 'Typed database models and persistence operations.' },
  { id: 'tensorflowjs', name: 'TensorFlow.js', category: 'Framework', description: 'Machine learning inference in the browser.' },
  { id: 'canvas', name: 'Canvas API', category: 'Graphics', description: 'Browser drawing surface for game and visual overlays.' },
  { id: 'html-css', name: 'HTML / CSS', category: 'Language', description: 'Semantic web structure and responsive presentation.' },
  { id: 'altair', name: 'Altair', category: 'Graphics', description: 'Declarative interactive statistical charts.' },
  { id: 'vader', name: 'VADER', category: 'Library', description: 'Bundled lexicon and rule-based sentiment scoring.' },
  { id: 'groq', name: 'Groq API', category: 'Service', description: 'Hosted model inference for generated explanations.' },
  { id: 'sqlite', name: 'SQLite', category: 'Database', description: 'Local file-based relational persistence.' },
  { id: 'framer-motion', name: 'Framer Motion', category: 'Library', description: 'Declarative React animation and interaction transitions.' },
  { id: 'docker', name: 'Docker', category: 'Platform', description: 'Containerized application and database environments.' },
  { id: 'pytest', name: 'pytest', category: 'Testing', description: 'Python automated service and regression tests.' },
  { id: 'unittest', name: 'unittest / AppTest', category: 'Testing', description: 'Python unit and Streamlit application regression checks.' },
  { id: 'github-actions', name: 'GitHub Actions', category: 'Automation', description: 'Repository-based automated quality and build workflows.' },
];
